name: Web - CI

on:
    pull_request:
        branches: [main]

defaults:
    run:
        working-directory: apps/web

jobs:
    format-lint-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            - name: Install dependencies
              run: npm i

            - name: Check formatting
              run: npm run format

            - name: Lint
              run: npm run lint -- --max-warnings=0

            - name: build
              run: npm run build
